version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/check-pins
    schedule:
      interval: weekly
    groups:
      actions-minor-patch:
        update-types: [minor, patch]
